# Generated by Django 2.0.4 on 2018-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MusicSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('album', models.ManyToManyField(to='music_type.Album')),
            ],
        ),
        migrations.AddField(
            model_name='musicsubtype',
            name='music_type',
            field=models.ManyToManyField(to='music_type.MusicType'),
        ),
    ]
