# Generated by Django 2.0.4 on 2018-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicsubtype',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='musictype',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
