# Generated by Django 2.0.4 on 2018-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_type', '0002_auto_20180403_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.CharField(default='', max_length=80),
        ),
    ]
