# Generated by Django 2.0.4 on 2018-04-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_type', '0004_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
