# Generated by Django 2.0.4 on 2018-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_type', '0005_delete_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictype',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='music_type',
            field=models.ManyToManyField(to='music_type.MusicType'),
        ),
    ]
